<?php
include_once('functions/themes.php');
include_once('functions/articles.php');
include_once('functions/clear.php');
include_once('functions/comments.php');
include_once('functions/misc.php');
include_once('functions/shortcodes.php');
include_once('functions/tags.php');
include_once('functions/widget.php');
include_once('functions/themeset.php');
include_once('functions/thumbnail.php');
?>
